### ISSUE TITLE
Isn't this an implementation of the PageObject pattern?

### ISSUE THREAD

**Issue by dandv** [xolvio/chimp-widgets#3]
[If](http://.martinfowler.com/bliki/PageObject.html) [so](https://code.google.com/p/selenium/wiki/PageObjects), it would help for SEO and credits at least, to have the words "page object" somewhere in the README. [Webdriver users have been looking for that](https://github.com/webdriverio/webdriverio/issues/583#issuecomment-115018821).

**Comment by DominikGuzei** [comment]
Hey @dandv, thanks for the feedback! I haven't seen this pattern before, nor did i know that it exists ;-)
But you're right, it's basically the PageObject pattern as described at the link you provided! I will add the link and a headline containing the words "page object", so that people are able to find it.

**Comment by ghost** [comment]
Note: With synchronous WebDriver.io testing, PageObjects become simple stateless singleton objects with methods.

``` js
var selectors = {
  myButton: '.myComponent .myButton'
}

widgets.myComponent = {
  triggerFunkyAction: function () {
    client.click(selectors.myButton);
  }
};
```

This gives autocompletion in WebStorm :-)

**Comment by DominikGuzei** [comment]
… which has the problem that you repeat `selectors.myButton` all the time, which is exactly what i wanted to avoid with my implementation. Components are not stateless, each one has a selector which is (transparently) used for all methods.

Btw… i remembered where i drew most my inspiration from, it's the [Pioneer.js](http://pioneerjs.com/) project :wink: But chimp-widgets also tries to stay much simpler than the bloated mess this became there!
